### ISSUE TITLE
[CTD]: X-Plane 11 crashes during landing roll

### ISSUE THREAD

**Issue by ymnoor21** [amyinorbit/x-uns-bugs#13]
### Version

1.0.9

### What happened?

# When did the crash occur?
Airport: **`VGBR`**
It's a very small regional airport with only two approaches available. I tried with both NDB 17 and NDB 35 approaches and CTD cannot be avoided.

# What was the FMS doing before the crash?
I was on NDB 17 approach this time and was flying manually to land. I touched down and went to **`DISC IDLE`** mode. As I was slowing down, X-Plane 11 seems to have paused for a millisecond and then continued and then crashed to the desktop. 

As far as I can remember I had no route discontinuity or no link in the FMS and I was flying directly to the Initial fix for NDB 17 **`(i.e FN17)`** from waypoint **`KAKBO`** when I took manual control of the aircraft and landed.

Note: Not sure if it is important, but I have had this kind of CTDs in v1.0.7, v.1.0.8, and now on v1.0.9. So I don't think it's a version issue, it's been happening all the time for me at these airports: **`VGBR`** and **`VGRJ`**.

# Attach your log file here
**CTD 1**. [Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7578473/Log.txt)
**CTD 2**. [Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7578708/Log.txt)

**Video Link with FMS showing**: https://www.youtube.com/watch?v=CFDKniBkncs

**Comment by amyinorbit** [comment]
Fixed in 1.0.10
