### ISSUE TITLE
Crash when entering hold data [CTD]: 

### ISSUE THREAD

**Issue by darrenwhitehouse** [amyinorbit/x-uns-bugs#17]
### Contact Details

darrenw264@gmail.com

### Version

1.09

### What happened?

# When did the crash occur?

Climbing between 10-20000 ft flying between EGPD and EGBB shortly after take off

# What was the FMS doing before the crash?
I was entering hold information to hold at MAPLE near EGBB when it CTD

# Attach your log file her
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7597206/Log.txt)
e

**Comment by amyinorbit** [comment]
Thanks for the report! Can you confirm whether this still happens on the latest version of the plugin?

**Comment by darrenwhitehouse** [comment]
Hi Amy, I'll have a check.Haven't flown in a while due to work demands but
will let you know!
