### ISSUE TITLE
[CTD]: after entering hold -> proceed and set another hold

### ISSUE THREAD

**Issue by jvp89** [amyinorbit/x-uns-bugs#18]
### Contact Details

jvp@meo.pt

### Version

1.09

### What happened?

# When did the crash occur? performing arrival at EGKK KIDLI1G arrival and 26L app requires two holds.

# What was the FMS doing before the crash? it was already out of the first holding(WILLO) and I had set the next one(MAY). 

# Attach your log file her
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7618376/Log.txt)

[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7618377/uns1_log.txt)

[WebFMC-log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7618378/WebFMC-log.txt)

**Comment by amyinorbit** [comment]
@jvp89 Can you let me know if you've encountered the same crash at all since 1.0.10? Ta!
