### ISSUE TITLE
[Bug]: UTC time off

### ISSUE THREAD

**Issue by nsargent76** [amyinorbit/x-uns-bugs#19]
### Contact Details

nsargent76@gmail.com

### Version

1.09

### What happened?

# What happened: 
The UTC on the FMS is off and my ETA time when corrected for local time is showing 00:00

# Expected behaviour
The UTC time should be showing14:07 as my t/o time, instead is show 20:07 and my LCL time shows 00:00 with a -5, EST, which is not close to correct.  My takeoff time is actually showing 12 hours ahead of my local time, so I was wheels up at 08:07 LCL and it shows my t/o UTC time as 20:07, 12 hours ahead of actual sim time.  Maybe there might be some correlation between the two.
# Attach your log file her
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7618759/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7618761/uns1_log.txt)

**Comment by nsargent76** [comment]
Also, on page 2 of the fuel page the LCL time should be editable with LS key L3 to make the time zone correction from UTC to LCL time.

**Comment by nsargent76** [comment]
![Screenshot (72)](https://user-images.githubusercontent.com/70915267/143897935-d3346292-a030-4277-b2c2-90a06cf09320.png) before times entered into the flight summery page

**Comment by nsargent76** [comment]
![Screenshot (74)](https://user-images.githubusercontent.com/70915267/143898132-0f25919c-422c-4311-9aba-60f9f41f3c27.png)  Added departure time to the FS page of the FP

**Comment by nsargent76** [comment]
![Screenshot (73)](https://user-images.githubusercontent.com/70915267/143898330-f264d1e9-1530-45cc-b652-61a49a95e971.png)  After adding the ETD to the FP page, you can see the LLC time has changed to 00:00

**Comment by nsargent76** [comment]
![Screenshot (76)](https://user-images.githubusercontent.com/70915267/143898842-d45d66bb-4774-4eb8-ad8d-240a98197c46.png)  After departure the times have changed, the show UTC is exactly 12 later than the actual local time.  That's odd and maybe it has something to do with the issue.

**Comment by amyinorbit** [comment]
Fixed in 1.0.10
