### ISSUE TITLE
[CTD]: After landing CTD due to UNS. No previous CTD issues.

### ISSUE THREAD

**Issue by IMatAMS** [amyinorbit/x-uns-bugs#20]
### Contact Details

itamarmazor@hotmail.com

### Version

1.09

### What happened?

Never had a single crash all these weeks, suddenly 2 chrashes in one evening.  First one in KSEA on the ground, while building flight plan

second one: 

# When did the crash occur?

Just after landing, turning off runway 05 KRDM

# What was the FMS doing before the crash?

Was flying the RNAV. pressed APPR act. on the UNS (because I had never tried that before). Found out that that doesn't work  for an RNP approach. So  continued visual approach. 

After landing just turning off the runway sudden CTD. Seemed to do one or two big stutters a few second before finally crashing

# Attach your log file her

[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7621308/uns1_log.txt)

[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7621309/Log.txt)

**Comment by amyinorbit** [comment]
Fixed in 1.0.10
