### ISSUE TITLE
[Bug]: Multiple Landin reports with identical data

### ISSUE THREAD

**Issue by jakobeng1303** [amyinorbit/x-uns-bugs#21]
### Version

1.09

### What happened?

# What happened
I did 2 flights (LOWW LIRF LOWW) and obviously 2 landings. After arriving at LOWW I noticed that the Landing page said 1/2 and wanted tos ee whether the UNS had remembered my first flight but it showed 2 times the identical info
https://i.imgur.com/vzq9rix.png
https://i.imgur.com/N7Genhb.png
# Expected behaviour
I would expect either just one landing info or at least the correct ones from each flight. While I do not remember what the landing page said after the first landing, at the time it looked somewhat correct and not like the info on the second landing. 
# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7626579/uns1_log.txt)

**Comment by amyinorbit** [comment]
Thanks for your report! This isn't how the page works, it only shows your current landing. The second landing page displays sensor drift values IRL, but since that isn't modelled at the moment it doesn't display anything. That might be added in the future.

**Comment by jakobeng1303** [comment]
I see, thanks
