### ISSUE TITLE
[Bug]: The time to waypoint gets cut off on the ND

### ISSUE THREAD

**Issue by JacobKre** [amyinorbit/x-uns-bugs#23]
### Contact Details

Discord: JacobK#9511

### Version

1.0.9

### What happened?

![image](https://user-images.githubusercontent.com/70914399/144719574-092b5d72-ec5c-40e9-9a07-60584527607c.png)

# What happened
The `2` on the time to the next waypoint got cut off on the right side of the ND
# Expected behaviour
The full time should be able to be seen on the ND
# Attach your log file he
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7654367/uns1_log.txt)

**Comment by amyinorbit** [comment]
Fixed in 1.0.11
