### ISSUE TITLE
[CTD]: Crosfill crashes to desktop

### ISSUE THREAD

**Issue by nsargent76** [amyinorbit/x-uns-bugs#3]
### Contact Details

nsargent76@gmail.com

### Version

1.08

### What happened?

# When did the crash occur?
when trying to sync info from FMS-1
# What was the FMS doing before the crash?
had just loaded up the aircraft
# Attach your log file her
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7549206/uns1_log.txt)
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7549212/Log.txt)

e

**Comment by amyinorbit** [comment]
Thanks for the report! Can you please add more details? What were you doing specifically, where did you trigger crosfill from, that kind of thing?
