### ISSUE TITLE
Instant SASL crash when using keyboard entry mode[Bug]: 

### ISSUE THREAD

**Issue by BluesmanEP** [amyinorbit/x-uns-bugs#30]
### Version

Aircraft verion 1.11

### What happened?

When using the keyboard entry mode in the UNS by clicking on the bottom right side screw, I get an instant SASL crash when pressing any key on the keyboard.

The keyboard mode activates correctly, the little icon shows in the bottom left corner of the screen, but as soon as I type any key SASL crashes, half the plane screens go blank and I get the following error message:
![image](https://user-images.githubusercontent.com/1726991/145748122-76954066-bd90-41d1-ab3b-9feffa0b1065.png)

This happens when first loading the plane, in flight, and after landing.

Logs attached
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7700805/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7700806/uns1_log.txt)
[SASLLog.txt](https://github.com/amyinorbit/x-uns-bugs/files/7700811/SASLLog.txt)
.

**Comment by amyinorbit** [comment]
SASL issue, fixed in 1.0.12
