### ISSUE TITLE
[CTD]: CTD after switch to DTO Page

### ISSUE THREAD

**Issue by DerKazar** [amyinorbit/x-uns-bugs#32]
### Contact Details

peter.hasse@yahoo.com

### Version

1.0.11

### What happened?

# When did the crash occur?

Cruise. EDDK to EDDH, near TOD, with sceneries for both airports & Ortho4XP. X-Enviro. Switched from PERF to DTO page after getting a Direct from Bremen Radar. About 2 seconds later, PC froze for about 5 - 10 seconds. Then X-Plane CTD and PC unfreeze.

# What was the FMS doing before the crash?

Being normal, I guess. XPNDR was not transmitting switch from STBY to Mode C to Swift (VATSIM Client) though. Manually forced it to Mode C via Swift.

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7711356/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7711357/uns1_log.txt)
[FlyWithLua_Debug.txt](https://github.com/amyinorbit/x-uns-bugs/files/7711363/FlyWithLua_Debug.txt)
[xEnviroLog.txt](https://github.com/amyinorbit/x-uns-bugs/files/7711365/xEnviroLog.txt)

**Comment by amyinorbit** [comment]
@DerKazar Thanks for the report. There's zero evidence of a crash in the logs, so nothing I can do sadly. The fact that it didn't crash immediately after switching to the DTO page, but after 2 seconds makes me think it's not related to the plane, but you never know.

I'll leave this ticket open, if it happens again please do let me know via comment and upload a new log!

**Comment by DerKazar** [comment]
I thought of something PC-related too as the logs just stops in the normal. So wilco, thanks for having a look!

**Comment by amyinorbit** [comment]
No problem at all, thanks for the report! Closing this for now, but please do comment here if it happens again and I'll reopen.
