### ISSUE TITLE
FUEL PAGE 3: RESERVES value wrong[Bug]: 

### ISSUE THREAD

**Issue by CMBelite-FR** [amyinorbit/x-uns-bugs#33]
### Version

1.12

### What happened?

# What happened
in the fuel page 3/5, the reserve value takes into account the extra fuel entered in fuel 1/5.

Currently: ALTERNATE + HOLD + EXTRA

# Expected behaviour

Should only take into account the ALTERNATE + HOLD fuel entered in fuel 1/5

https://cdn.discordapp.com/attachments/903996995595821087/920394279405367306/unknown.png

**Comment by amyinorbit** [comment]
Thanks for the report! Fixed in next version.
