### ISSUE TITLE
[CTD]: Arrival to KSEA prior to starting the approach

### ISSUE THREAD

**Issue by coastpilot** [amyinorbit/x-uns-bugs#35]
### Version

1.0.11

### What happened?

# When did the crash occur?
At cruise prior to beginning the arrival.
# What was the FMS doing before the crash?
All seemed normal, FMS had just updated after passing COUGA waypoint.
# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7728980/uns1_log.txt)

**Comment by amyinorbit** [comment]
According to the log that's not a crash caused by the UNS-1, the back trace only contains X-Plane itself. Closing it for now, if it occurs again with the same conditions please comment here 🙂

**Comment by coastpilot** [comment]
Howdy, understood. Was trying to replicate a CTD a friend mentioned and
when it happened along the same route he'd been flying I figured I should
add to his report just in case :-)
