### ISSUE TITLE
[CTD]: FMS CTD

### ISSUE THREAD

**Issue by canuk22** [amyinorbit/x-uns-bugs#37]
### Version

1.11 and 1.12

### What happened?

# When did the crash occur? While programming the FMC, as soon as I click on del for a "no link", it hapenned twice on both versions 1.11 and 1.12

# What was the FMS doing before the crash? I was programming it, specifically deleting a no link

# Attach your log file here 
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7738510/uns1_log.txt)

**Comment by amyinorbit** [comment]
Duplicate, same cause as #28. fixed in next version
