### ISSUE TITLE
[CTD]: Before touchdown

### ISSUE THREAD

**Issue by JetNoise61** [amyinorbit/x-uns-bugs#40]
### Version

latest avail, v1.12

### What happened?

# When did the crash occur? 
Short prior touchdown. EPKK, RNAV 25, about 10 feet. Got a bunch of spurious GlideSlope and Terrain warnings, while being spot on path ...

# What was the FMS doing before the crash?
./.

# Attach your log file her
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7747069/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7747071/uns1_log.txt)

ADD INFO:  1st sign of the CTD was a 1 seconds freeze of XPlane, then recovering, then immediatly after touchdown/rollout -> CTD

Oliver, aka JetNoise

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@859c2d3d
