### ISSUE TITLE
[CTD]: Deleting waypoints, UNS freeze then CTD

### ISSUE THREAD

**Issue by DuckWhsiperer** [amyinorbit/x-uns-bugs#43]
### Version

1.0.11

### What happened?

#Crash happen
Flying EGBB to LOWI, FL250, Approx 25mi from TOD
# What was the FMS doing before the crash?
Was deleting multiple waypoints from the star, sim stuttered after deleting approx the 4th, UNS 1 then froze and CPT ND went blank. UNS 2 would still change pages. When I went to edit the Flight plan in UNS2 the sim CTD (straight crash, no hanging).
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7785981/Log.txt)
 [](url)
# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7785982/uns1_log.txt)

**Comment by amyinorbit** [comment]
Thanks for the report. I can't do much without knowing the exact route, STAR and approach, could you please add them here?

**Comment by DuckWhsiperer** [comment]
Of course, it was the MADEB1B, RNP Z 26 
ADMEX Y321 EMKUK UL612 COWLY Q70 BIG UL9 KONAN UL607 KOK M150 PITES DCT EDISA DCT BATUB M738 MADEB 

Appox between BATUB and OSDOV

**Comment by amyinorbit** [comment]
Fixed in update 1.0.15
