### ISSUE TITLE
[CTD]: FMS CTD when pressing "Appr" button upon Final Approach to ILS

### ISSUE THREAD

**Issue by WilburPilot** [amyinorbit/x-uns-bugs#44]
### Version

1.0.11

### What happened?

# When did the crash occur? 
I have purchased v 1.12 FJS Q4XP a few days ago. Tried landing it twice at YSSY (the route was YPMQ to YSSY) using ILS16L. After first familiarising myself with the new FMS (ILS tuning, switching from FMS to ILS in PFD etc.) upon the approach the program first froze then crashed to desktop (specifically after pressing the "Appr" button on the FCU) just prior to entering the ILS cone near the WYPT "TONUX". This happened twice in the same sequence/manner. I have not tried flying it since. I have very few add ons (AviTab, RXP GTN, Better Pushback, SAM, Traffic Global) and all of them work perfectly with all other third party aircraft, e.g. TOLISS A321, Falcon 50EX, Eclipse 550NG, Bell Helicopter 429.

# What was the FMS doing before the crash?
The FMS appeared to be following the flight as programmed (as far as I can tell, remembering that I am not an expert and I am new to this plane and its FMS, but do have some experience with the FMS on the TOLISS A321)
The fact that the FJS Q4XP is very complex, has great detail and hence potential for immersion is what attracted me to it. I know there is a lot to learn here, but CTD so early in the learning process are naturally disappointing. I am hoping this issue has an easy fix and am grateful for your advice.

# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7787341/uns1_log.txt)

**Comment by WilburPilot** [comment]
Thanks Amy, because I am new here I interpret the label you added in your response "fixed-in-next" as that the fault I encountered is real and is in the process of being fixed in the subsequent version of the uns-1 software.

**Comment by amyinorbit** [comment]
Indeed 🙂

**Comment by WilburPilot** [comment]
Great, thanks. (I am learning)😊
