### ISSUE TITLE
[Bug]: FMS Datarefs no longer work with SmartCopilot

### ISSUE THREAD

**Issue by zachbf** [amyinorbit/x-uns-bugs#48]
### Version

1.0.12

### What happened?

# What happened
Nearly all smartcopilot commands work via the dataref. A few anomolies that need to be brought up in another forum (eg. LHS nav source dataref won't work but RHS does work). However, none of the FMS refs will work.

# Expected behaviour
Like most other datarefs, would except smartcopilot commands to trigger button presses on the FMS. 
The FMS was working prior to the dataref changes that occured in December (from memory) although the FMS dataref pathways did not appear to change.
webFMC seem to have this sorted, unless there is another backend method that they are using to manipulate the FMS.

# Attach your log file her
[log files.zip](https://github.com/amyinorbit/x-uns-bugs/files/7811033/log.files.zip)
e

**Comment by amyinorbit** [comment]
There are commands for the FMS keys, not datarefs. The old datarefs were a byproduct of how the animation system worked, and not created by the plugin itself.

You’ll have to change your smartcopilot profile to use commands instead, that’s what WebFMC uses. If SmartCopilot doesn’t see the commands that’s a problem on their side.

**Comment by zachbf** [comment]
Thanks for the information.

Reference the #commands section of the [smartCopilot site](https://sky4crew.com/hangar), are the functions written into the FMS in such a way that the commands would not be transmitted by smartCopilot?

**Comment by zachbf** [comment]
Sorry - I should added that I've previously been using [COMMANDS] with smartCopilot, not clicks. I was just experimenting and this was the file attached.

**Comment by jwhitey2035** [comment]
I am also working with Zach on the config. SmartCopilot mention on their website a limitation with commands (picture attached). Just so we can isolate the root issue (and know for sure its not a problem with our config file), @amyinorbit could you please confirm the command is coded as seen below (and hence, the reason why SmartCopilot can't see the command).
![SmartCP](https://user-images.githubusercontent.com/97148120/148167402-5d7ac48f-558d-477c-a258-2a4c944ebbac.jpg)

**Comment by amyinorbit** [comment]
@jwhitey2035 it is not, the commands are all coded to return 1, so they can be intercepted. They do however only do something in the `xplmPhaseBegin` (`0`) phase.

**Comment by rhard** [comment]
> @jwhitey2035 it is not, the commands are all coded to return 1, so they can be intercepted. They do however only do something in the `xplmPhaseBegin` (`0`) phase.

Hi @jwhitey2035, can you post a little more details about your last post? Does it mean in the command handlers, you react only on the ```xplmPhaseBegin```?

There should be something unusual with the commands on your side. If we understand the behavior, we can adjust SmartCopilot logic.

**Comment by jwhitey2035** [comment]
@amyinorbit @rhard above is the main dev for smart copilot. Would you be able to answer his question re: reacting only to `xplmphasebegin`.
Thanks :)

**Comment by zachbf** [comment]
I have reviewed smartcopilot logs. I can confirm all other commands are being sent and received, but when clicking the FMS buttons they are not received or transmitted. I also tried using the pop-out FMS.

See screenshot attached: https://puu.sh/IB77c/51f6489bb9.png

It's strange that it would pickup every single other aircraft command but not the FMS ones.

**Comment by rhard** [comment]
@amyinorbit  SmartCopilot reacts only to the ```xplm_CommandBegin``` and ```xplm_CommandEnd``` and ignores ```xplm_CommandContinue```. Could be the problem here?

@zachbf Are you sure the commands are found at all? Can you check the smartcopilot.log (not dev log) for any ```Can't find command in block``` messages?

**Comment by jwhitey2035** [comment]
> 

@rhard There are no messages like that in the smartcopilot.log. Commands are definitely there, can see them being triggered when pressing and viewing commands on the datareftool, but they are just not being detected by smart copilot at all.

**Comment by rhard** [comment]
I will give you the new beta with raw command logging to check what happened here.

**Comment by rhard** [comment]
@zachbf @jwhitey2035  Please try b3 and check the dev log for any `Command handler` messages.
[smartcopilot.zip](https://github.com/amyinorbit/x-uns-bugs/files/7829079/smartcopilot.zip)

**Comment by jwhitey2035** [comment]
> @rhard we are only seeing Command Handlers for the commands that were working before (i.e. Control Lock, overhead switches etc). FMS commands are still not showing up in log (even though being captured by the DataRefTool viewer).
![image](https://user-images.githubusercontent.com/97148120/148621617-504ddec3-b80c-42eb-b890-11a24ff2fa9f.png)

**Comment by jwhitey2035** [comment]
@rhard We also have been able to send the Manip for the FMS keys for the animation, but the command itself is not working still. So button animation moves, but no action on the FMS.

**Comment by rhard** [comment]
Can you post config file, please.

**Comment by jwhitey2035** [comment]
> Can you post config file, please.

Find attached. We are now working with .yaml format as we are on the SC4 Beta. Cheers
[Q400YAMLSmartCopilot.zip](https://github.com/amyinorbit/x-uns-bugs/files/7833014/Q400YAMLSmartCopilot.zip)

**Comment by rhard** [comment]
Try this beta with different commands (not only FMS), and send me a log file. Need to be sure we do not break existing functionality
[smartcopilot.zip](https://github.com/amyinorbit/x-uns-bugs/files/7833038/smartcopilot.zip).

**Comment by jwhitey2035** [comment]
> Try this beta with different commands (not only FMS), and send me a log file. Need to be sure we do not break existing functionality [smartcopilot.zip](https://github.com/amyinorbit/x-uns-bugs/files/7833038/smartcopilot.zip).

@rhard Good news and bad news from this version.

**Good news:** FMS commands are now detected and sent to partner by smart copilot.

**Bad news**: Every command is constantly being sent as on/off close to 30 times per second. So buttons are continually pressing on/off, switches flicking on/off rapidly even though master has only turned or pressed once. See attached log for details

[devlogq400.zip](https://github.com/amyinorbit/x-uns-bugs/files/7833100/devlogq400.zip)

**Comment by rhard** [comment]
Yes, could be expected. I think I understand what going on here. Will make a fix.

**Comment by rhard** [comment]
Check b5 please.
[smartcopilot.zip](https://github.com/amyinorbit/x-uns-bugs/files/7833172/smartcopilot.zip)

**Comment by zachbf** [comment]
It works!!! 😄

**Comment by jwhitey2035** [comment]
> Check b5 please. [smartcopilot.zip](https://github.com/amyinorbit/x-uns-bugs/files/7833172/smartcopilot.zip)

Working, thank you!

Now just to get these power levers working and it'll be done!

**Comment by rhard** [comment]
Good! For joy fix, I need a little more time. Here is the issue: https://github.com/Sky4Crew/smarcopilot-issues/issues/1
