### ISSUE TITLE
[Bug]: Negative values can't be entered for local time

### ISSUE THREAD

**Issue by TimFoxxo** [amyinorbit/x-uns-bugs#49]
### Version

1.13

### What happened?

# What happened  -> When trying to enter a negative number for the local time on the Flight Plan Summary or second fuel page it autamitacally changes it to the same number but positiv. I have this issue since 1.12.

# Expected behaviour -> That the negative number gets accepted 

# Attach your log file here:

[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7820735/Log.txt)

**Comment by amyinorbit** [comment]
Fixed in commit 6692ba55 (uns1)
