### ISSUE TITLE
[CTD]: X-Plane crash when reaching a holding fix after the initial entry

### ISSUE THREAD

**Issue by rjb4000** [amyinorbit/x-uns-bugs#5]
### Version

UNS-1 - version 1.0.4

### What happened?

# When did the crash occur?
I programmed a simple flight plan and added a holding maneuver at the last fix. I then selected DTO the holding fix where the NAV page showed TO: The holding fix, Next: the hold. Q400 entered the holding pattern using a sort-of parallel entry, then flew inbound to the holding fix as expected. On reaching the fix and right at the moment I would expect UNS to sequence from the entry to the holding pattern itself, X-Plane crashed.

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7558198/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7558202/uns1_log.txt)

**Comment by amyinorbit** [comment]
@rjb4000 Has this issue occurred at all since 1.0.10?

**Comment by rjb4000** [comment]
Hi @amyinorbit - I just tried it out on 1.12 and the UNS performed perfectly! Thanks for the fix!
