### ISSUE TITLE
[Bug]: UNS did not produce End of Flight page after second landing

### ISSUE THREAD

**Issue by TheFreedReed** [amyinorbit/x-uns-bugs#50]
### Version

1.0.12

### What happened?

# What happened
UNS did not produce the end of flight page after landing. This was the second flight with flightplan deletion in between turnarounds.
I actually don't remember if it did it after the first leg or not, sorry Amy.

# Expected behaviour
Was expecting to see the end of flight page, but I'm no expert.

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7838483/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7838501/uns1_log.txt)

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1#1a748892

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@1a748892
