### ISSUE TITLE
[CTD]: ATC Reroute causes spontaneous combustion whilst holding short

### ISSUE THREAD

**Issue by TubaMirabilis** [amyinorbit/x-uns-bugs#54]
### Version

Aircraft v.1.14

### What happened?

# When did the crash occur?

Before line-up and takeoff.

# What was the FMS doing before the crash?

I loaded an RNAV SID SMLTZ2 via RWY 9L at KATL whilst parked at the gate.  When I got to the runway ATC re-cleared via ATL9 SID radar vectors to SOTWO then YUESS.  I figured that I could probably use HDG as my lateral mode for departure but I wanted to get SOTWO into the waypoints list so that I could go direct promptly if asked.  I tried to append SOTWO to the currently loaded list of FIXs but upon presssing the ENTER key the sim sound stuttered once and then the CTD triggered a few seconds later.  This all happened 24 hours ago so I can't really remember which buttons I pressed in which order; I was rushing a bit trying not to lose my place in the queue for departure.

# Attach your log file
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7878196/Log.txt)
 here

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@e89353d9
