### ISSUE TITLE
[Bug]: X-Plane 11 Unresponsive/Crash after entering replay mode and moving slider.

### ISSUE THREAD

**Issue by kieranharvey** [amyinorbit/x-uns-bugs#57]
### Version

1.0.12

### What happened?

# What happened - After landing, and still on APU power on stand with doors shut, I entered replay mode via the menu. After adjusting the slider to move back to a previous point in time in the flight (landing) XP11 becomes unresponsive and crashes.

# Expected behaviour - To enter replay mode and watch back the landing without issue.

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7920636/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7920637/uns1_log.txt)

SIDE NOTE

I have had crashes while flying the dash lately that in the log point to the following DLLs:
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\SYSTEM32\ntdll.dll

The UNS log seems to point to these two as well in this instance?

Thanks,
Kieran. :)

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@0e58d86

**Comment by amyinorbit** [comment]
Further fixes in amyinorbit/uns1@a2427430
