### ISSUE TITLE
[Bug]: perf page, local time

### ISSUE THREAD

**Issue by Fabioburgos** [amyinorbit/x-uns-bugs#58]
### Version

1.14

### What happened?

# What happened
When i put -5 utc in performance page in order to see the eta at local time, it take +5 not -5, so the local time are showing as utc +5 not utc -5.
# Expected behaviour

# Attach your log file here

**Comment by amyinorbit** [comment]
Thanks for the report, fixed in the new update (should be out in a couple days)
