### ISSUE TITLE
[CTD]: Crash on final

### ISSUE THREAD

**Issue by EK1288** [amyinorbit/x-uns-bugs#59]
### Version

1.5

### What happened?

# When did the crash occur? 
CTD on final, just before touchdown. 

# What was the FMS doing before the crash? 
I had programmed an RNAV approach but then decided to use the ILS approach instead at OLBA Rwy 16. I disabled the AP at ~1000ft to hand fly the final, and the crash happened a bit later at around 300/400 feet. 

# Attach your log file here 
Attached.

[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7961293/Log.txt)

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@6020d777
