### ISSUE TITLE
LOWI standard climb-out LNAV issue [Bug]: 

### ISSUE THREAD

**Issue by jakobeng1303** [amyinorbit/x-uns-bugs#6]
### Version

1.08

### What happened?

# What happened
I was departing LOWI on the KOGOL3J SID. The KOGOL SID uses the standard non-rnav climb-out to RTT [LOWI SID chart](https://charts.vacc-austria.org/LOWI/LOWI_Departure_SID%20RWY%2008_07102021.pdf) or chart 10-3 Navigraph. Theoretically ocu climb outbound on 063 radial of OEJ until reaching 9500ft, upon which you turn to RTT. 
However, I crossed 9500ft before D7.0 OEJ and even after crossing it and having been above 10k, the plane did not turn to RTT but the fictional WPT 13.6 DME OEJ. This point does not exist and should not frankly. I guess this is a Navigraph issue but what happened next is definitely  UNS related. 
The planed turned to the left to RTT but because of the proximity was unable to fly to RTT, gave up and continued on a westerly heading (until I manually proceeded direct KOGOL).

what happened vs what it should have looked like: 
https://i.imgur.com/Ms8vKjc.png

# Expected behaviour
The issue with the imaginary point is probably nav related and should be fixed by NG but the dct turn thereafter should not be the case. 
# Attach your log file here
I will try to attach the log once I finished the flight but it is part of a mulitleg flight so yeah :/ ..
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7562515/uns1_log.txt)

**Comment by amyinorbit** [comment]
Only part of this is unexpected behaviour.

Conventional SIDs should *always* be checked against the coding. In this case, the databases codes a path all the way to the hold at `RTT`. ARINC424 (the underlying standard that defines how procedures are coded) does not have a way to encode waypoints that are bypassed entirely. It's the pilot's job to then input a direct-to when necessary, or more likely when told to do so by ATC.

There *is* an issue here with the DF leg to RTT (the leg right before the hold). I'll have a look at that!

**Comment by amyinorbit** [comment]
![Screenshot 2021-12-09 at 19 29 45](https://user-images.githubusercontent.com/1282972/145463466-243a4568-e455-4f7c-8cdb-7a6a582bbda1.png)

Fixed in the next version. You'd never fly the whole procedure IRL but the FMS will give it its best
