### ISSUE TITLE
[CTD]: in cruise with incorrect TOD alert

### ISSUE THREAD

**Issue by jamlen** [amyinorbit/x-uns-bugs#61]
### Version

1.0.13

### What happened?

# When did the crash occur?
In cruise >300nm from TOD

# What was the FMS doing before the crash?
On VNAV page

# Attach your log file here
[SASLLog.txt](https://github.com/amyinorbit/x-uns-bugs/files/7994880/SASLLog.txt)
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7994881/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7994882/uns1_log.txt)

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@6020d777
