### ISSUE TITLE
[CTD]: Crash after increasing prop to max during flight

### ISSUE THREAD

**Issue by EK1288** [amyinorbit/x-uns-bugs#63]
### Version

1.15

### What happened?

# When did the crash occur? 

Flight level change during cruise. I pushed the prop to max and the Sim crashed. I shelved the Q4XP after my last CTD (also reported here), decided to retry it, and now CTD again - quite frustrating. Note that I haven't experienced CTDs with any of the other addons I've recently been using. 

# What was the FMS doing before the crash? 

Nothing notable. Flight was mid-cruise. 

# Attach your log file here

[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8033333/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8033335/uns1_log.txt)

**Comment by EK1288** [comment]
Thanks for the quick response Amy - happy to provide more info, just let me know what you'd like me to provide. I've attached the SASL log in case helpful. I've also found a file called stack_trace.txt in my main XP11 directory. This seems to be from the last crash I reported and not this most recent one, based on the file's date. 
[SASLLog
[stack_trace.txt](https://github.com/amyinorbit/x-uns-bugs/files/8038011/stack_trace.txt)
.txt](https://github.com/amyinorbit/x-uns-bugs/files/8037989/SASLLog.txt)

**Comment by amyinorbit** [comment]
Hiya! Looking at the stacks trace again, that looks like a driver crash to me -- nothing I can do about that I'm afraid! Please keep reporting crashes if they keep happening 🙂
