### ISSUE TITLE
[CTD]: Crash when commencing to AF leg

### ISSUE THREAD

**Issue by PF2020** [amyinorbit/x-uns-bugs#64]
### Version

1.0.13

### What happened?

# When did the crash occur?
on approach - onto RJAF via VOR RWY18 with LNAV and VS mode. I made one time hold at MBE for descent then DTO to MBE, followed the approach. When commencing to the AF leg(12DME ARC), the route disappeared on the ND and HSI showed the last tracking course. however, the plane was not followed AF and continue make left turn few seconds, FMS hangup and can't popup then CTD. I try the approach 3 times, got CTD twice in the same sequence.

I don't have CTD at teardrop approach ever, however this procedure has AF leg.
# What was the FMS doing before the crash?
After passed IF(MBE), only set ALT for descent(6700ft, 4900ft). not used VNAV after IF.
# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8049657/uns1_log.txt)
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8049658/Log.txt)
[stack_trace.txt](https://github.com/amyinorbit/x-uns-bugs/files/8049659/stack_trace.txt)

**Comment by amyinorbit** [comment]
Hello! Thanks for your report. I have been trying to reproduce the crash without success. You say the plane crashed twice out of the three times you attempted to reproduce it -- can you think of anything you did differently the one time it didn't?

**Comment by PF2020** [comment]
Hi! thanks for your response and I want to help solve the problem. Yes, I have no idea but I'm thinking why the results were different.
Here is my experience.
1) Inbound from South via airway then approach with VNAV CDO - Success.
2) Inbound from North via airway then procced 1time HOLD by manually(HDG mode and timer. without LNAV). Insert approach in FMS while holding, direct MBE... - CTD.
3) Inbound from west, make 1time HOLD then proceed. Enter all routes including the approach before takeoff - CTD As my the report. 

In the case of CTD, happened in the same sequence(CI to AF). However, the details are different. Umm...

I feel the instability of the processing related to CI or VI LEG. For example, When following TIGER2 DEP from RJOO(non-RNAV departure) , SID require to intercept YOE R291 after ITE R201 but sometimes the plane flying VI LEG(HDG261) forever...FMS show me "INTC". no CTD.
On the other hand, when transit to another leg in approach, maybe need VNAV recalculation. Isn't that one of the reasons for CTD? Of course, it's my guess.

**Comment by PF2020** [comment]
Here is tracker log case"1" and "2" by BlackBox flightlogger. If it helps even a little visually for you.
Can see that it is making a further left turn in case"2".
![log](https://user-images.githubusercontent.com/99492547/153940469-ffb466d9-b6c6-4c7e-a278-ed6c4158a80f.jpg)
.

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@6020d777
