### ISSUE TITLE
[Bug]: CTD when enabling BC mode on the autopilot

### ISSUE THREAD

**Issue by HighbrowA** [amyinorbit/x-uns-bugs#65]
### Version

1.0.13

### What happened?

# What happened
CTD when enabling BC mode on the autopilot. This happens every time on the AND VOR (112.200) (Airport: ENAN). Not sure if it happens on other VORs aswell, but happens here each time I try,
# Expected behaviour
Well, not crash :)
# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8103852/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8103854/uns1_log.txt)

**Comment by amyinorbit** [comment]
Thanks for the report. It shouldn't crash indeed, looking into it. That being said, you are not supposed to fly back course with VORs -- you should tune the correct radial instead. IRL (and once this is fixed), BC will not engage when a VOR (and not a LOC) is tuned

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@432d4365
