### ISSUE TITLE
[CTD]: Passenger weight on fuel page 

### ISSUE THREAD

**Issue by sparrowlondon** [amyinorbit/x-uns-bugs#66]
### Version

Latest

### What happened?

I am getting crashes when I make a mistake inputting my passenger number on the fuel page. 

It appears that I can edit both the passenger number and total weight of passengers. If I enter 59 and then accidentally enter 59 again I end up with a passenger count of 59, a total weight of 59 and then a kg of @ 1 which I can't edit. My attempts to input different numbers to fix the problem result in a crash. I've made this mistake and got a crash more than once.

[Logq4xp.txt](https://github.com/amyinorbit/x-uns-bugs/files/8209121/Logq4xp.txt)

Thank you for your help Amy, I'm sorry I broke your FMS!

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@8fbbec09
