### ISSUE TITLE
[Bug]: Fligh time summary appear inmeadiatly lift of

### ISSUE THREAD

**Issue by Fabioburgos** [amyinorbit/x-uns-bugs#75]
### Version

1.18

### What happened?

# What happened
Flight time summary appear in FMS just in lift off
# Expected behaviour
Flight time summary appears prior landing
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8500564/Log.txt)

# Attach your log file here

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@9659b777
