### ISSUE TITLE
[CTD]: RNAV approach, CTD when 20 feet above the ground. 

### ISSUE THREAD

**Issue by mason23zh** [amyinorbit/x-uns-bugs#77]
### Version

1.18

### What happened?

# When did the crash occur?
This was my route: DCT MARNR MARNR7, RNAV Z 16L approach, GRIFY transition. The sim was feezed around 1 second when I was about 100 feet AGL, and CTD happened when I was 20 AGL.

# What was the FMS doing before the crash?
After I set up the RNAV approach, I changed the altitude for some waypoints in the approach (I know I shouldn't do that, just wanna see how vnav perfor): I changed altitude from x6000 to @6000 for GRIFY, x3202 to @3202 for KARFO and x1900 to @1900 for DGLAS. I set up VNAV target vs rate to -1500. I let the aircraft descend via the VNAV path after the KARFO, before that I was using VS, for somehow, vnav just wasn't descend fast enough, passed DGLAS around 2500 MSL, and I disconnected flow manually fro
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8518664/Log.txt)
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8518666/uns1_log.txt)
m that point. 
# Attach your log file here

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@6020d777
