### ISSUE TITLE
[Bug]: NANSHU2 departure out of RJFK turns the wrong direction

### ISSUE THREAD

**Issue by GiacomoLaw** [amyinorbit/x-uns-bugs#78]
### Version

Latest

### What happened?

# What happened
Aircraft initially turns right, however then starts going left on the departure.

![image](https://user-images.githubusercontent.com/9038673/164675176-9df7e343-ab55-42d8-9e42-5d0c9f173e25.png)

# Expected behaviour
![image](https://user-images.githubusercontent.com/9038673/164675102-5ce4f29e-df07-4f76-b285-1e5b09acfa9e.png)

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/xnav@e6e04be
