### ISSUE TITLE
[CTD]: Flying into KEAT

### ISSUE THREAD

**Issue by nperl10** [amyinorbit/x-uns-bugs#8]
### Contact Details

noah.hellcat@gmail.com

### Version

Unknown

### What happened?

[](url)# When did the crash occur?
Flying into KEAT
# What was the FMS doing before the crash?
Doing a Arch approach
# Attach your log file
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7573987/Log.txt)
 here

**Comment by amyinorbit** [comment]
Fixed in 1.0.10
