### ISSUE TITLE
[CTD]: Approach into Biarritz

### ISSUE THREAD

**Issue by DuckWhsiperer** [amyinorbit/x-uns-bugs#82]
### Version

1.0.15

### What happened?

# When did the crash occur?
CTD (Blue report to laminar screen) 
During missed apporach as FMS sequenced between runway and the first waypoint on the missed approach. 

Approach was the RNP RWY 09 at LFBZ, FMS did not initiate the glide path on final and remained at 2400ft (VNAV profile showed below profile even at 4 miles (2400ft) at around 2mile DME to the VOR I started to climb to the missed approach altitude. 

On this same flight when debarting EGBB on  DTY4F from RW33 the FMS failed to intersept the Daventry radial and just continued on the 118 heading (displaying 10,800 miles on the ND) 

# What was the FMS doing before the crash?
As above 

# Attach your log file here
[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8800617/uns1_log.txt)
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/8800618/Log.txt)

**Comment by amyinorbit** [comment]
Thanks for the report, I'll look into it.

The DTY4F issue is already fixed for the next version, please make sure to keep one issue per report for bookkeeping 🙂

**Comment by DuckWhsiperer** [comment]
Thanks Amy, I saw the DTY4F was fixed I just wanted to include it incase it proved to be part of the reason for the later issues. :)

Just noticed that Volanta seems to have lost connection right at the end of the Runway which may indicate it happened right above the RW waypoint. Thanks again for all your hard work 

![image](https://user-images.githubusercontent.com/68589569/171056318-17fcda74-7181-456f-ad78-dfd7712dae67.png)
