### ISSUE TITLE
[CTD]: Direct to waypoint not in FPL

### ISSUE THREAD

**Issue by TubaMirabilis** [amyinorbit/x-uns-bugs#84]
### Version

1.19

### What happened?

# When did the crash occur?
Descending and under radar vectors to CYYZ RWY 24L
# What was the FMS doing before the crash?
I had prepared waypoints leading up to RWY 24R. These were LIPUX AMILU EBDAL & NOAHA.  Suddenly ATC says to switch to RWY 24L direct to LISDU.  I go to the DTO page, type LISDU, press ENTER, set NX to 15 because the highest number occupied at the time was 14 and X-Plane crashed.

# Attach your log file her
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/9224035/Log.txt)
e

**Comment by amyinorbit** [comment]
Fixed in amyinorbit/uns1@0164a8ce
