### ISSUE TITLE
[CTD]: CTD when enter ILS freq in TUNE page and click 'ENTER'

### ISSUE THREAD

**Issue by mason23zh** [amyinorbit/x-uns-bugs#89]
### Version

XP11 V1.24

### What happened?

# When did the crash occur?
During the approach in EGCC ILS 23R

# What was the FMS doing before the crash?
I was entering ILS freq in the TUNE page for both NAV1 and NAV2, and after clicking the 'ENTER' than CTD happened.
Procedure: 
1) Enter ILS freq for NAV1 (left fmc)
2) Enter ILS freq for NAV2 (left fmc)
3) Hold FORMAT to set the course for the left
4) Hold FORMAT to set the course for the right
4) Click NAV1 again (left fmc)
5) Click ENTER (left fmc) -> CTD

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/9969443/Log.txt)

**Comment by amyinorbit** [comment]
No stack trace in the log, can't action sadly. Do reopen if you can reproduce it and get a new log.
