### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kontoal** [amyinorbit/x-uns-bugs#9]
### Contact Details

kontogiannisal@gmail.com

### Version

UNS-1 - version 1.0.9

### What happened?

# What happened My root was from LGAV to LGSM. I forgot to make vnav desent . I did it manually arranging the flight level with vs button. I dissengaged A/P 5 miles before toucdown and i was flying manualy. A few seconds after touch down the simulator freeze and i had a CDT. I wasnt look at the FMS that moment. Thank you and sory for my english

# Expected behaviour

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7575216/Log.txt)

[uns1_log.txt](https://github.com/amyinorbit/x-uns-bugs/files/7575217/uns1_log.txt)

**Comment by amyinorbit** [comment]
Fixed in 1.0.10
