### ISSUE TITLE
[CTD]: Crashing after aircraft activation. 

### ISSUE THREAD

**Issue by Kothnaaken** [amyinorbit/x-uns-bugs#93]
### Version

Latest

### What happened?

# When did the crash occur? As soon as the aircraft is loaded after activation. Sim won't get far enough in to do anything before it does. Possibly an OpenGL bug?

# What was the FMS doing before the crash? n/a

# Attach your log file here
[Log.txt](https://github.com/amyinorbit/x-uns-bugs/files/10071542/Log.txt)

**Comment by amyinorbit** [comment]
Not a FMMS crash, and no crash indication in log. Closing.
