### ISSUE TITLE
[CTD]: CTD after activation, OpenGL related (XP11)

### ISSUE THREAD

**Issue by Kothnaaken** [amyinorbit/x-uns-bugs#94]
### Version

Latest

### What happened?

# When did the crash occur? After activating and reloading/restarting XP with OpenGL enabled. Vulkan seems to fix the crashing, though performance is significantly reduced in Vulkan. I do have the latest Radeon drivers and had attempted with the last version before updating last night.

# What was the FMS doing before the crash? Unknown, crashing before getting any access to it. Log mentions it, though.

# Attach your log file here
[Log (1).txt](https://github.com/amyinorbit/x-uns-bugs/files/10071843/Log.1.txt)

**Comment by amyinorbit** [comment]
Driver crash with none of our plugins in the stack trace -- can't do anything about that, sorry!
